config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notifications#index"

  resources :notifications, only: %i[create index show update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def create
    notification = Notification.create
    notification.broadcast_prepend_to('notifications_for_1',
                                      target: 'notifications',
                                      partial: 'notifications/notification',
                                      locals: { notification: })
  end

  def index
    @notifications = Notification.all
  end

  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def update
    notification = Notification.find(params[:id])
    notification.update(read: true)

    redirect_to notification_path(notification), status: 303
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notifications</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notifications/_notification.html.erb
<% text = notification.read ? 'read' : 'unread' %>

<%= button_to("#{text} #{notification.id}", notification_path(notification), method: :patch, form: { data: { turbo: false, controller: 'fixup-csrf' } }) %>

app/views/notifications/_push_notification.html.erb
<turbo-frame id="moocow-<%= notification.id%>" src="<%= notifications_path %>" />

app/views/notifications/index.html.erb
<turbo-frame id="awesome">
  <%= turbo_stream_from 'notifications_for_1' %>

  <div id='notifications'>
    <%= render partial: 'notifications/notification', collection: @notifications %>
  </div>

  <%= button_to('Create new notification', notifications_path, method: :post) %>
</turbo-frame>

app/views/notifications/show.html.erb
<turbo-frame id="awesome">
  <div>I am a notification</div>
</turbo-frame>